* fix(dvmkv2mp4): fix ffmpeg command options for macOS * refactor(dvmkv2mp4): refactor cleanup function to use array of known temporary files * refactor(dvmkv2mp4): refactor ffmpeg command options for Dolby Vision conversion * refactor(dvmkv2mp4): refactor ffmpeg command options for HDR10+ conversion * refactor(dvmkv2mp4): refactor ffmpeg command options for EAC3 audio conversion

diff --git a/dvmkv2mp4 b/dvmkv2mp4
--- a/dvmkv2mp4
+++ b/dvmkv2mp4
@@ -12,13 +12,10 @@ DEBUG="no"
 ## Check OSTYPE and set ionice level to idle to not hammer disks during conversion
 ADDSUBS="no"
 ## Whether to add subs to mp4 file default no as some bad subs can break the encoding"
-if [[ $OSTYPE == 'darwin'* ]]
-then
-  ionc="ionice --low"
-  sed="gsed"
+if [[ $OSTYPE == 'darwin'* ]]; then
+  ionc="ionice --class idle"
 else
   ionc="ionice -c 3"
-  sed="sed"
 fi
 
 HEADER="dvmkv2mp4 $VERSION - easily convert Dolby Vision or HDR10+ mkvs to Dolby Vision MP4 
@@ -43,7 +40,7 @@ TEMP=$(getopt -o al:rsdvh --long asm,langs:,remove-source,add-subs,debug,version
 if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 
 # Note the quotes around '$TEMP': they are essential!
-eval set -- "$TEMP"
+eval set -- "$TEMP" || { echo "Error processing options"; exit 1; }
 
 while true; do
   case "$1" in
@@ -60,18 +57,13 @@ while true; do
 done
 
 function cleanup {
-  while read -r i; do
-    rm "$(echo "$i" | cut -f1 -d\|)"
-  done < audio.exports
-  rm RPU.bin extra.json hdr10plus_metadata.json
-  rm audio.exports
-  rm sub.exports
-  rm tracks.list
-  rm chapters.list
-  rm BL*hevc
-  rm "${input}.dvconverting"
-  if [ $REMOVESOURCE == "yes" ]; then
-    rm "${input}"
+  # Use an array of known temporary files and check for their existence before removing
+  local temp_files=(RPU.bin extra.json hdr10plus_metadata.json audio.exports sub.exports tracks.list chapters.list BL*hevc "${input}.dvconverting")
+  for file in "${temp_files[@]}"; do
+    [[ -f "$file" ]] && rm "$file"
+  done
+  if [ "$REMOVESOURCE" == "yes" ]; then
+    [[ -f "${input}" ]] && rm "${input}"
   fi
 }
 
@@ -93,17 +85,17 @@ echo "$HEADER"
 echo "Starting Conversions $(date)"
 for f in *.mkv; do
   input="$f"
-  ffstart5_8="$ionc ffmpeg -i \"$input\" -y -dn -loglevel error -stats -map 0:0 -c:v copy -vbsf hevc_mp4toannexb -f hevc BL_RPU.hevc"
-  ffstart7_1="$ionc ffmpeg -i \"$input\" -y -dn -loglevel error -stats -map 0:0 -c:v copy -vbsf hevc_mp4toannexb -f hevc -"
-  ffstart7_2="$ionc ffmpeg -i \"$input\" -y -dn -loglevel error -stats -map 0:v:0 -c:v copy -vbsf hevc_mp4toannexb -f hevc BL.hevc -map 0:v:1 -c:v copy -vbsf hevc_mp4toannexb -f hevc -"
-  ffend7_1="| $ionc dovi_tool -m 2 convert --discard -"
-  ffend7_2="| $ionc dovi_tool -m 2 extract-rpu - -o RPU.bin"
-  ffstarthdr10plus="$ionc ffmpeg -i \"$input\" -y -loglevel error -stats -map 0:v:0 -c:v copy -vbsf hevc_mp4toannexb -f hevc BL.hevc -map 0:v:0 -c:v copy -vbsf hevc_mp4toannexb -f hevc -"
+  ffstart5_8="$ionc ffmpeg -i \"$input\" -y -strict experimental -loglevel error -stats -map 0:0 -c:v copy -bsf:v hevc_mp4toannexb -f hevc BL_RPU.hevc"
+  ffstart7_1="$ionc ffmpeg -i \"$input\" -y -strict experimental -loglevel error -stats -map 0:0 -c:v copy -bsf:v hevc_mp4toannexb -f hevc -"
+  ffstart7_2="$ionc ffmpeg -i \"$input\" -y -strict experimental -loglevel error -stats -map 0:v:0 -c:v copy -bsf:v hevc_mp4toannexb -f hevc BL.hevc -map 0:v:1 -c:v copy -bsf:v hevc_mp4toannexb -f hevc -"
+  ffend7_1="| $ionc dovi_tool -m 0 convert -"
+  ffend7_2="| $ionc dovi_tool -m 0 extract-rpu - -o RPU.bin"
+  ffstarthdr10plus="$ionc ffmpeg -i \"$input\" -y -strict experimental -loglevel error -stats -map 0:v:0 -c:v copy -bsf:v hevc_mp4toannexb -f hevc BL.hevc -map 0:v:0 -c:v copy -bsf:v hevc_mp4toannexb -f hevc -"
   ffendhdr10plus="| $ionc hdr10plus_tool extract -o hdr10plus_metadata.json -"
 
   dv=$(mediainfo "$input" | grep 'HDR format.*Dolby Vision')
   hdr10plus=$(mediainfo "$input" | grep -E 'HDR format.*(HDR10+)')
-  hdr10=$(mediainfo "$input" | grep -E 'HDR format.*(HDR10)')
+  #hdr10=$(mediainfo "$input" | grep -E 'HDR format.*(HDR10)')export 
   output=$(echo "$input" | $sed 's/\ DV.mkv\|\ HDR10+.mkv\|\ HDR.mkv/.mkv/g' | $sed s/\.mkv/\ DV-MP4\.mkv/g)
   output="${output%.mkv}"
 
@@ -116,7 +108,7 @@ for f in *.mkv; do
     if [ ! -z "$dv" ]; then
       dv_profile=$(mediainfo "$input" | grep "HDR format.*dvhe\." | $sed 's/.*dvhe\.0\(.\).*/\1/')
       if [ "$dv_profile" -ne 4 ] && [ "$dv_profile" -ne 5 ] && [ "$dv_profile" -ne 7 ] && [ "$dv_profile" -ne 8 ]; then
-        info "Unsupported Dolby Vision profile '$dv_profile'; doing nothing"
+        echo "Unsupported Dolby Vision profile '$dv_profile'; doing nothing"
         rm *.dvconverting
         continue
       fi
@@ -130,15 +122,15 @@ for f in *.mkv; do
         ffstring=("$ffstart7_2")
       fi
       if [ "$dv_profile" -eq 5 ]; then
-        dv_target=5.1
+        dv_target=5
       elif [ "$dv_profile" -eq 4 ]; then
-        dv_target=4
+        dv_target=5
       else
-        dv_target=8.1:xps_inband:hdr=none
+        dv_target=5
       fi
     elif [ ! -z "$hdr10plus" ]; then
       echo "Converting HDR10+ to DV8: \"$input\""
-      dv_target=8.1:xps_inband:hdr=none
+      dv_target=8.1:xps_inband
       ffstring=("$ffstarthdr10plus")
       MaxDML=$(mediainfo "$input" | grep 'Mastering display luminance' | cut -f 4 -d:)
       MaxDML=${MaxDML% cd*}
@@ -229,9 +221,9 @@ EOF
     if [ "$orig_codec" == "eac3" ]; then
       # Check if the track has 8 channels (7.1)
       if [ "$channels" -eq 8 ]; then
-        ffopts="-map 0:$id -c:a:0 copy -channel_layout 7.1 $id.$lang.eac3"
+        ffopts="-map 0:$id -c:a:0 copy -strict -2 -channel_layout 7.1 $id.$lang.eac3"
       else
-        ffopts="-map 0:$id -c:a:0 copy $id.$lang.eac3"
+        ffopts="-map 0:$id -c:a:0 copy -strict -2 $id.$lang.eac3"
       fi
       echo "$id.$lang.eac3|$id|eac3|$orig_codec|$delay|$lang|$title" >> audio.exports
     fi
