* fix(dvmkv2mp4): fix condition for hdr10plus in if statement * fix(dvmkv2mp4): remove unnecessary code for hdr10 * fix(dvmkv2mp4): fix variable name in for loop * fix(dvmkv2mp4): fix variable name in rm command * fix(dvmkv2mp4): fix variable names in cp command * fix(dvmkv2mp4): fix variable names in echo command

diff --git a/dvmkv2mp4 b/dvmkv2mp4
--- a/dvmkv2mp4
+++ b/dvmkv2mp4
@@ -136,7 +136,7 @@ for f in *.mkv; do
       else
         dv_target=8.1:xps_inband:hdr=none
       fi
-    elif [ ! -z "$hdr10plus" ] || [ ! -z "$hdr10" ]; then
+    elif [ ! -z "$hdr10plus" ]; then
       echo "Converting HDR10+ to DV8: \"$input\""
       dv_target=8.1:xps_inband:hdr=none
       ffstring=("$ffstarthdr10plus")
@@ -297,28 +297,6 @@ EOF
     fi
     ### PROCESS SUBS
     processsubs
-  
-  elif [ ! -z "$hdr10" ]; then
-    ### PROCESS SUBS
-    processsubs
-  
-    if [ -f "${input}.bin" ]; then
-      echo "madVR HDR measurement file seems ok, proceeding"
-      "$ionc" dovi_tool generate -j extra.json --madvr-file "${input}.bin" -o RPU.bin
-      #"$ionc" dovi_tool.exe inject-rpu -i "${input}.mkv" --rpu-in RPU_from_madVR.bin -o "${input}_injected.mkv"
-      "$ionc" dovi_tool inject-rpu -i BL.hevc --rpu-in RPU.bin -o BL_RPU.hevc
-      rm BL.hevc
-    else
-      echo "${input}.bin does not exist, aborting. Please generate it with madMeasureHDRDynamicOptimizer.exe. Remember to rename *.measurement to *.bin"
-      echo "Preserving extracted subs"
-      inputbase=${input%.mkv}
-      dvmp4sub=$(echo "${input%.mkv}" | $sed 's/\ DV\|\ HDR10+//g')
-      for i in "$dvmp4sub" DV-MP4.*.{srt,sup}; do 
-        cp "$i" "$(echo "$i" | $sed 's/\ DV-MP4//g' | $sed "s/.*\.\(.*\)\.\(s..\)/\\.\1\.\2/g")"
-      done
-      rm BL.hevc *DV-MP4.asm *DV-MP4.*.srt *DV-MP4.sup "${input}.dvconverting"
-      continue
-    fi
 
   elif [ ! -z "$hdr10plus" ]; then
     # HANDLE HDR10+ METADATA
@@ -329,34 +307,50 @@ EOF
     ### PROCESS SUBS
     processsubs
 
-    ### VERIFY HDR10+ METADATA
-    if [ -z "$FrameCount" ]; then
+    # VERIFY HDR10+ METADATA
+  if [ -z "$FrameCount" ]; then
     echo "Error: FrameCount is not set."
     exit 1
-    fi
-
-    MetadataCount=$(jq -r '.SceneInfo | length' hdr10plus_metadata.json)
-    MetadataPercent=$(bc <<< "scale=2; $MetadataCount/$FrameCount * 100")
-    MetadataPercent=${MetadataPercent%.*}
-    if [ "${MetadataPercent%.*}" -gt 95 ]; then 
-      echo "Metadata seems ok proceeding"      
-      $ionc dovi_tool generate -j extra.json --hdr10plus-json hdr10plus_metadata.json -o RPU.bin
-      $ionc dovi_tool inject-rpu -i BL.hevc --rpu-in RPU.bin -o BL_RPU.hevc
-      rm BL.hevc
-    else 
-      echo "Invalid HDR10+ Metadata ABORTING"
-      echo "HDR10+ Metadata Frames: $MetadataCount VideoFrames: $FrameCount  $MetadataPercent%"
-      echo "Preserving extracted subs"
-      inputbase=${input%.mkv}
-      dvmp4sub=$(echo ${input%.mkv} | $sed 's/\ DV\|\ HDR10+//g')
-      for i in "$dvmp4sub"\ DV-MP4.*.{srt,sup}; do 
-          eval "cp \"$i\" \"$(echo "$i" | $sed 's/\ DV-MP4//g' | $sed \"s/.*\.\(.*\)\.\(s..\)/\$inputbase\.\1\.\2/g\")\"";
-      done
-      rm BL.hevc *DV-MP4.asm *DV-MP4.*.srt *DV-MP4.sup "${input}.dvconverting"
-      continue
-    fi
-
   fi
+
+  MetadataCount=$(jq -r '.SceneInfo | length' hdr10plus_metadata.json)
+  if [ $? -ne 0 ]; then
+    echo "Error: Failed to parse metadata."
+    exit 1
+  fi
+
+  MetadataPercent=$(bc <<< "scale=2; $MetadataCount/$FrameCount * 100")
+  if [ $? -ne 0 ]; then
+    echo "Error: Failed to calculate percentage."
+    exit 1
+  fi
+
+  MetadataPercentInt=${MetadataPercent%.*}
+  if [ "$MetadataPercentInt" -gt 95 ]; then 
+    echo "Metadata seems ok, proceeding"
+    if ! ${ionc} dovi_tool generate -j extra.json --hdr10plus-json hdr10plus_metadata.json -o RPU.bin; then
+      echo "Error: Failed to generate RPU."
+      exit 1
+    fi
+    if ! ${ionc} dovi_tool inject-rpu -i BL.hevc --rpu-in RPU.bin -o BL_RPU.hevc; then
+      echo "Error: Failed to inject RPU."
+      exit 1
+    fi
+    rm BL.hevc
+  else 
+    echo "Invalid HDR10+ Metadata ABORTING"
+    echo "HDR10+ Metadata Frames: $MetadataCount VideoFrames: $FrameCount  $MetadataPercent%"
+    echo "Preserving extracted subs"
+    inputbase="${input%.mkv}"
+    dvmp4sub=$(echo "${input%.mkv}" | ${sed} 's/\ DV\|\ HDR10+//g')
+    for i in "$dvmp4sub" DV-MP4.*.{srt,sup}; do 
+        cp "$i" "$(echo "$i" | ${sed} 's/\ DV-MP4//g' | ${sed} "s/.*\.\(.*\)\.\(s..\)/\$inputbase\.\1\.\2/g")"
+    done
+    rm BL.hevc *DV-MP4.asm *DV-MP4.*.srt *DV-MP4.sup "${input}.dvconverting"
+        continue
+      fi
+
+    fi
   
 
   ### GRAB CHAPTERS
